jobs:

- name: job
  plan:
  - task: task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      params:
        BRANCH: ((branch))
        ENVIRONMENT: ((environment))
        AUTOPROMOTE: ((autopromote))
      run:
        path: sh
        args:
        - -exc
        - |
          echo This is $BRANCH on $ENVIRONMENT, and it will $AUTOPROMOTE.


