jobs:

- name: job
  plan:
  - task: task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - exc
        - |
          echo hello

