---
#@ load("@ytt:data", "data")
resources:

- name: instance-variables
  type: git
  icon: github
  source:
    uri: https://github.com/klas-s/instance-variables.git

jobs:

#@ for/end environment in environments:
- name: #@ "job-for-" + environment
  plan:
  - get: instance-variables
    trigger: ((autopromote))
  - task: task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      params:
        AUTOPROMOTE: ((autopromote))
        BRANCH: ((branch))
        ENVIRONMENT: #@ environment
      run:
        path: sh
        args:
        - -exc
        - |
          echo This is $BRANCH on $ENVIRONMENT, and it will $AUTOPROMOTE.
